# Generated by Django 5.2.1 on 2025-06-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDietHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('goal', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=20)),
                ('recommended_diet', models.CharField(max_length=50)),
                ('initial_weight', models.FloatField()),
                ('final_weight', models.FloatField()),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('waist_before', models.PositiveSmallIntegerField()),
                ('waist_after', models.PositiveSmallIntegerField()),
                ('hips_before', models.PositiveSmallIntegerField()),
                ('hips_after', models.PositiveSmallIntegerField()),
                ('chest_before', models.PositiveSmallIntegerField()),
                ('chest_after', models.PositiveSmallIntegerField()),
                ('food_likes', models.TextField()),
                ('food_dislikes', models.TextField()),
                ('diet_type_used', models.CharField(max_length=50)),
                ('satisfaction_level', models.PositiveSmallIntegerField()),
                ('success', models.CharField(max_length=3)),
                ('estimated_lean_mass', models.FloatField()),
            ],
        ),
    ]
