# Generated by Django 5.2.1 on 2025-06-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('sex', models.CharField(max_length=10)),
                ('goal', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=20)),
                ('predicted_diet', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
