# Generated by Django 5.2.1 on 2025-06-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_ai', '0002_predictionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiethistory',
            name='calories_deficit',
            field=models.PositiveSmallIntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdiethistory',
            name='macro_carbs',
            field=models.PositiveSmallIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdiethistory',
            name='macro_fat',
            field=models.PositiveSmallIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdiethistory',
            name='macro_protein',
            field=models.PositiveSmallIntegerField(default=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdiethistory',
            name='success',
            field=models.CharField(max_length=10),
        ),
    ]
