# Generated by Django 5.2.1 on 2025-06-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_ai', '0003_userdiethistory_calories_deficit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiethistory',
            name='calories_deficit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdiethistory',
            name='macro_carbs',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdiethistory',
            name='macro_fat',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdiethistory',
            name='macro_protein',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
