# Generated by Django 5.2.1 on 2025-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_ai', '0004_alter_userdiethistory_calories_deficit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiethistory',
            name='chest_after',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userdiethistory',
            name='chest_before',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userdiethistory',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userdiethistory',
            name='hips_after',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userdiethistory',
            name='hips_before',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userdiethistory',
            name='waist_after',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userdiethistory',
            name='waist_before',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userdiethistory',
            name='weight',
            field=models.FloatField(),
        ),
    ]
