# Generated by Django 5.2.1 on 2025-06-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_ai', '0005_alter_userdiethistory_chest_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='feedback',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
