# Generated by Django 5.2.1 on 2025-05-13 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Мъж'), ('female', 'Жена'), ('other', 'Друго')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField(help_text='Височина в сантиметри')),
                ('weight', models.FloatField(help_text='Текущо тегло в кг')),
                ('wish_weight', models.FloatField(help_text='Желано тегло в кг')),
                ('activity_level', models.CharField(choices=[('none', 'Без активност'), ('low', '1-3 пъти седмично (ниска активност)'), ('medium', '3-5 пъти седмично (средна активност)'), ('high', '6-7 пъти седмично (висока активност)')], max_length=10)),
                ('goal_date', models.DateField(blank=True, help_text='Дата до която иска да постигне желаното тегло', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
