# Generated by Django 5.2.1 on 2025-05-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
