# Generated by Django 5.2.1 on 2025-05-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_food_food_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('breakfast', 'Закуска'), ('lunch', 'Обяд'), ('snack', 'Следобедна закуска'), ('dinner', 'Вечеря')], max_length=30, unique=True, verbose_name='Тип хранене')),
            ],
            options={
                'verbose_name': 'Тип хранене',
                'verbose_name_plural': 'Типове хранения',
            },
        ),
    ]
