# Generated by Django 5.2.1 on 2025-05-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_mealtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('none', 'Без активност'), ('low', '1-3 пъти седмично (ниска активност)'), ('medium', '3-5 пъти седмично (средна активност)'), ('high', '6-7 пъти седмично (висока активност)'), ('very_active', 'Активна работа')], max_length=30),
        ),
    ]
