# Generated by Django 5.2.1 on 2025-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='carbs_target_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fats_target_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='protein_target_g',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
