# Generated by Django 5.2.1 on 2025-06-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_carbs_target_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wish_weight',
            field=models.FloatField(blank=True, help_text='Желано тегло в кг', null=True),
        ),
    ]
