# Generated by Django 5.2.1 on 2025-06-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_wish_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightlog',
            options={'ordering': ['-data_recorded']},
        ),
        migrations.RenameField(
            model_name='weightlog',
            old_name='weigth',
            new_name='weight',
        ),
    ]
