# Generated by Django 5.2.1 on 2025-06-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_weightlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightlog',
            name='weight',
        ),
        migrations.AddField(
            model_name='weightlog',
            name='new_weight',
            field=models.FloatField(blank=True, help_text='Ново тегло в кг', null=True),
        ),
        migrations.AddField(
            model_name='weightlog',
            name='new_wish_weight',
            field=models.FloatField(blank=True, help_text='Ново целево тегло в кг', null=True),
        ),
        migrations.AddField(
            model_name='weightlog',
            name='old_weight',
            field=models.FloatField(blank=True, help_text='Старо тегло в кг', null=True),
        ),
        migrations.AddField(
            model_name='weightlog',
            name='old_wish_weight',
            field=models.FloatField(blank=True, help_text='Стара целево тегло в кг', null=True),
        ),
    ]
