# Generated by Django 5.2.1 on 2025-06-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_weightlog_weight_weightlog_new_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default='друго', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamins_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
