# Generated by Django 5.2.1 on 2025-06-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_food_category_food_vitamins_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text='Град за климатична корекция', max_length=100),
        ),
    ]
