# Generated by Django 5.2.1 on 2025-06-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='carbs_target_g',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='daily_calories',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fats_target_g',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='protein_target_g',
        ),
    ]
