# Generated by Django 5.2.1 on 2025-05-26 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeficit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_deficit', models.FloatField(help_text='Дневен калориен дефицит в kcal')),
                ('protein_deficit', models.FloatField(help_text='Протеини в грамове')),
                ('carbs_deficit', models.FloatField(help_text='Въглехидрати в грамове')),
                ('fats_grams', models.FloatField(help_text='Мазнини в грамове')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_dailydeficit',
            },
        ),
    ]
