# Generated by Django 5.2.1 on 2025-05-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailydeficit',
            table=None,
        ),
    ]
