# Generated by Django 5.2.1 on 2025-06-12 14:57

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_meal_mealitem_progresshistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailydeficit',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='progresshistory',
            options={'ordering': ['date_recorded']},
        ),
        migrations.AddField(
            model_name='dailydeficit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique_for_date='user'),
        ),
        migrations.AddField(
            model_name='dailydeficit',
            name='total_calories',
            field=models.FloatField(default=0, help_text='Общо изядени калории днес'),
        ),
        migrations.AlterUniqueTogether(
            name='dailydeficit',
            unique_together={('user', 'date')},
        ),
    ]
