# Generated by Django 5.2.1 on 2025-06-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_alter_dailydeficit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydeficit',
            name='city',
            field=models.CharField(blank=True, help_text='Град за климатична корекция', max_length=100),
        ),
        migrations.AddField(
            model_name='dailydeficit',
            name='daily_water_goal',
            field=models.FloatField(default=0.0, help_text='Персонализирана дневна цел за вода в литри'),
        ),
    ]
