# Generated by Django 5.2.1 on 2025-06-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_waterlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterlog',
            name='amount_ml',
            field=models.PositiveIntegerField(default=0, help_text='Изпито количество вода (в ml)'),
        ),
    ]
