# Generated by Django 5.2.1 on 2025-07-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_alter_dailydeficit_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressHistory',
        ),
    ]
